name: Morning Brief

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          WEATHER_API: ${{ secrets.WEATHER_API }}
          NEWS_API: ${{ secrets.NEWS_API }}
          OPENAI_API: ${{ secrets.OPENAI_API }}
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python main.py
